spring.application.name = property-management
#Google Cloud Project ID
google.client.id=365618537849-p5551olai5hgv64uunt0v9087876hpdf.apps.googleusercontent.com
#dev
pms.dummy = This is a dummy for the dev environment
#server-port
server.port = 8080
# DB URL and DB name
spring.datasource.url = jdbc:postgresql://localhost:5432/pmsdb-dev?ssl=false
# DB username
spring.datasource.username = pmuser
# DB pass
spring.datasource.password = 12345
# DB driver
#spring.datasource.driverClassName = org.postgresql.Driver
# Tells to keep existing data/tables on restart; 'create' drops and recreates everything
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.open-in-view = false
spring.jpa.show-sql = true
##Hibernate properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.jdbc.time_zone = UTC
spring.jackson.serialization.fail-on-empty-beans = false