# DB URL and DB name
spring.datasource.url=jdbc:postgresql://localhost:5432/pmsdb-prod?ssl=false
# DB username
spring.datasource.username=postgres
# DB pass
spring.datasource.password=@01MsL
# DB driver
#spring.datasource.driverClassName=org.postgresql.Driver
# Tells to keep existing data/tables on restart; 'create' drops and recreates everything
spring.jpa.hibernate.ddl-auto=update
# SQL logging - keep off in production
#spring.jpa.show-sql=true
# Line 11 is commented bcs we dont want to see SQL queries on production
##Hibernate properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresqlInnoDBDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.serialization.fail-on-empty-beans=false